import os

SECRET_KEY = os.getenv("SECRET_KEY")
SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE")
SQLALCHEMY_TRACK_MODIFICATIONS = True
REDIS_URL = os.getenv("REDIS")
FILE_DIR = os.getenv("FILE_DIR")
FILE_SERVER_DOMAIN = os.getenv("FILE_SERVER_DOMAIN")
